name: Check Pull Request

on:
  push:
    branches-ignore:
      - main

jobs:
  format:
    name: Check format
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1

      - name: Install dependencies
        run: bun install

      - name: Check format
        run: bun run format:check
  lint:
    name: Check lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1

      - name: Install dependencies
        run: bun install

      - name: Check lint
        run: bun run lint
  build:
    name: Check build
    runs-on: ubuntu-latest
    env:
      TZ: "Asia/Tokyo"
      SERVER_URL: ${{ vars.SERVER_URL }}
      CREDITS: ${{ vars.CREDITS }}
    steps:
      - uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1

      - name: Install dependencies
        run: bun install

      - name: Check build
        run: bun run build
  check-type:
    name: Check type
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1

      - name: Install dependencies
        run: bun install

      - name: Check type
        run: bun run check-type
